### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by Dahlgren**
Example build with artifacts, https://github.com/Dahlgren/SQF-Assembly/actions/runs/1019909059

### CODE REVIEW

**Comment by mwpowellhtx** [comment]
So... This fixes the build issue?

**Comment by Dahlgren** [comment]
This PR adds CI that builds Windows binaries. Linux is currently not working.

**Comment by mwpowellhtx** [comment]
Any ideas why Linux is not working? I could not get the Windows to build, so perhaps some gaps could be explained there.

**Comment by Dahlgren** [comment]
Some parts of SQF-Assembly and ArmaScriptProfiler only supports MSVC

**Comment by mwpowellhtx** [comment]
Not sure what that means; the error I get building has nothing to do with MSVC. It is because there is a `..\..\..\programs\bench.c` missing. I did have to re-target the CMake configured projects, however, so I do not know if there were side effects from that, for the Windows 10 SDK, and C++ v142, IIRC.

**Pull request merged**
